### ISSUE TITLE
CIC mode online capture packet sometimes successful, sometimes unsuccessful.

### ISSUE THREAD

**Issue by doxuanthanh95** [ahlashkari/CICFlowMeter#101]
I run mode online to capture packet realtime, but I have 1 problem: when i start capture the packet on my card network, i see log is printed on my main screen, but I run for the second time, third time it doesn't print log on my screen, but fourth time, it may be capture packet and print my screen.
Please help me this bug !!!

**Comment by ltkhang** [comment]
Hi,

Please provide some pictures to illustrate your problems.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
