### ISSUE TITLE
How you executed DRDoS attacks includes NTP, DNS...? Why these attacks in CICDDoS2019 dataset have random ports?

### ISSUE THREAD

**Issue by theYTQ** [ahlashkari/CICFlowMeter#104]
For example, this is DRDoS_NTP, and its port is not 123.
![image](https://user-images.githubusercontent.com/51431481/98764094-08c5e700-2416-11eb-87e4-a60888af764e.png)
This is DRDoS_SNMP, and its port is not 161.
![image](https://user-images.githubusercontent.com/51431481/98764154-2abf6980-2416-11eb-909e-99e315d9ed9d.png)

**Comment by Magic-Doufu** [comment]
I also see many records with zero SYN FLAG COUNTS in the SYN attack files.
Maybe the attack records includes records after the service dies?
CICIDS2019 included reflection attack. (NTP/DNS are reflection attacks, probably the reason for random ports.)

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
