### ISSUE TITLE
Eclipse and Jnetpcap

### ISSUE THREAD

**Issue by msrose85** [ahlashkari/CICFlowMeter#105]
Hi,

I downloaded an older version of cicflowmeter which worked great. This new version includes Jnetpcap and eclipse, but there is no mention of them in the readme. What do they do? And how do you recreate the functionality of the old version (i.e. turn a PCAP into a time flow feature csv).

Thanks - sorry this may be obvious but i'm fairly new to this.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
