### ISSUE TITLE
ARP detection error

### ISSUE THREAD

**Issue by javieradelgado** [ahlashkari/CICFlowMeter#106]
I've found a "problem" (Maybe its my fault because I didn´t configure CICflowmeter the right way) when you get a PCAP with ARP traffic through CICflowmeter.

For some reason, CICflowmeter misinterprets ARP flows and thinks they are TCP flows.

Here is an example:

![arp_error](https://user-images.githubusercontent.com/71897497/102803918-52143980-43b9-11eb-8978-fad23789577d.jpg)

I have this PCAP where we can see normal ARP packets.  The thing is that some of the parameters in this packets are misunderstood and therefore misinterpreted, you can see I´ve marked some bytes with a red rectangle at the bottom of the image, they are the ones I will use to show the problem. 

When I get this PCAP through CICflowmeter, I get the following output:

![arp_error_libreoffice](https://user-images.githubusercontent.com/71897497/102804082-8e479a00-43b9-11eb-8277-65001f789a0d.jpg)

You can see I've marked 2 flows with yellow rectangles, this flows consist of minsundersood ARP packets. You can see the same numbers I´ve highlighted in the first image being considered SrcIP and DstIP when the really are ARP parameters.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
