### ISSUE TITLE
CICFlowmeter doesn't recognize pcap file.

### ISSUE THREAD

**Issue by tungnat97** [ahlashkari/CICFlowMeter#107]
[Link](https://cloudstor.aarnet.edu.au/plus/s/ds5zW91vdgjEj9i/download?path=%2FRaw_datasets%2FRaw_Network_dataset%2FNetwork_dataset_pcaps%2Fnormal_attack_pcaps%2Fnormal_scanning&files=normal_scanning6.pcap) to pcap file. When using `cfm` to extract features from this pcap file it yells 'Please select pcap file!'.

Running on Ubuntu 16.04.

**Comment by djzdjzdl** [comment]
Check your file header, if it is pcap-ng change pcap using editcap.exe
