### ISSUE TITLE
Does CICFlowMeter not support *.pcapng file?

### ISSUE THREAD

**Issue by Cyan95** [ahlashkari/CICFlowMeter#108]

**Comment by marksniper** [comment]
No, it doesn't support the pcapng extension. You could open the pcapng file via Wiresharsk and save it as pcap.

**Comment by aouinizied** [comment]
@Cyan95 or you can use NFStream framework which supports pcapng format.
Github repository: https://github.com/nfstream/nfstream

**Comment by souravs17031999** [comment]
@aouinizied does NFStream supports all features which cicflowmeter supports ?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
