### ISSUE TITLE
CICFlowMeter can not get flow label

### ISSUE THREAD

**Issue by FinTecher-code** [ahlashkari/CICFlowMeter#109]
![2021-01-10_192736](https://user-images.githubusercontent.com/26902168/104121544-f3b7f680-5379-11eb-923d-7a2b2851f7f1.png)
I upload the .pcap,but I get csv file without labels

**Comment by djzdjzdl** [comment]
Literally "No Label" with hard coded at BasicFlow.java. You can put some filter condition at BasicFlow.java If you want to labeling.

**Comment by aouinizied** [comment]
@jxb123 or you can use NFStream framework which integrates nDPI as source of a reliable label.

Github repository: https://github.com/nfstream/nfstream

**Comment by FinTecher-code** [comment]
Thank you for your reply.------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月11日(星期二) 晚上10:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ahlashkari/CICFlowMeter] CICFlowMeter can not get flow label (#109)

**Comment by banzhuanle** [comment]
你要自己设置过滤条件添加标签

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
