### ISSUE TITLE
False calculation of total number of ACK, SYN and other flags

### ISSUE THREAD

**Issue by Jaidip** [ahlashkari/CICFlowMeter#11]

**Comment by ahlashkari** [comment]
CICFlowmeter has two options to remove the short and not complete flows. So, the number of flags that you want should not be the same after process.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
