### ISSUE TITLE
Warning:~/libjnetpcap.so which might have disabled stack guard. The VM will try to fix the stack guard now.

### ISSUE THREAD

**Issue by LQun9601** [ahlashkari/CICFlowMeter#114]
The project runs on the 32-bit Linux(must be 32-bit). Now I get the warning :

Java HotSpot(TM) Server VM warning: You have loaded library /home/tom/work/CIC3/CICFlowMeter-master/jnetpcap/linux/jnetpcap-1.4.r1425/libjnetpcap.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

The warning caused the network card to fail to be accessed. 
How to do it?
Thanks.

**Comment by harman1989** [comment]
> The project runs on the 32-bit Linux(must be 32-bit). Now I get the warning :
> 
> Java HotSpot(TM) Server VM warning: You have loaded library /home/tom/work/CIC3/CICFlowMeter-master/jnetpcap/linux/jnetpcap-1.4.r1425/libjnetpcap.so which might have disabled stack guard. The VM will try to fix the stack guard now. It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
> 
> The warning caused the network card to fail to be accessed. How to do it? Thanks.

did you solve it?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
