### ISSUE TITLE
CICFlowMeter doesn`t work when the input file over 1GB

### ISSUE THREAD

**Issue by mark12138** [ahlashkari/CICFlowMeter#119]
when i use a *.pacp file over 1GB as CICFlowMeter`s input , it only gives 263 flows .

How can i solve this problem?

**Comment by aouinizied** [comment]
@mark12138 CicFlowMeter do not handle large files and have some memory issues. Did you try NFStream as an alternative processing tool?

**Comment by mark12138** [comment]
> @mark12138 CicFlowMeter do not handle large files and have some memory issues. Did you try NFStream as an alternative processing tool?

I will try , Thanks a lot.

**Comment by meriemferdjouni** [comment]
> @mark12138 CicFlowMeter do not handle large files and have some memory issues. Did you try NFStream as an alternative processing tool?

Hi @aouinizied, how many flow features the NFStream can extract?

Thank you.

**Comment by aouinizied** [comment]
88 features which include also nDPI based labels.
Moreover, you can extend it easily with Plugins as described here: https://www.nfstream.org/docs/api#nfplugin

**Comment by benholden09** [comment]
Is there any way to use NFstream to produce data in the same format as the CIC-IDS2017 data set format?

**Comment by lion10** [comment]
@aouinizied I split the pcap files into smaller using editcap tool, and the CICFlowMeter works fine, but I am not sure if is it a good way to split the pcap file or not. what do you think?
Thank you

**Comment by abmnyuiwari** [comment]
> @aouinizied I split the pcap files into smaller using editcap tool, and the CICFlowMeter works fine, but I am not sure if is it a good way to split the pcap file or not. what do you think? Thank you

i already try this way but when i want to convert my split data using this CICflowmeter, the program was autoclose not respond :(

**Comment by meriemferdjouni** [comment]
@abmnyuiwari I think any tool for splitting PCAP files should be fine. You can also check _SplitCap_. It is a free tool to split large PCAPs into smaller ones based on a criterion you select.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
