### ISSUE TITLE
CICFLOWMETER V3.0 shows ICMP protocol number 0 instead of 1

### ISSUE THREAD

**Issue by shumon2030** [ahlashkari/CICFlowMeter#122]
Hello: I converted ICMP traffic using CICFLOWMETER 3.0. In Wireshark, I can see the IP protocol for ICMP is 1 but the converted CSV file shows protocol#0.  Any advise?

**Comment by yorhaha** [comment]
If you still pay attention to this project, welcome to refer to my forked repository: 

https://github.com/blueice-thu/CICFlowMeter. 

Your issue has been resolved in my repository. I will improve the project and resolve as many issues as possible recently. Welcome for suggestions. :)

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
