### ISSUE TITLE
请问cicflowmeter可以处理ipv6的流量么（it can be used to handle IPv6 traffic？）

### ISSUE THREAD

**Issue by banzhuanle** [ahlashkari/CICFlowMeter#123]
以及，我pcap包里输入3w个数据包，cicflowmeter导出的csv文件只整合了1745条流量特征，这正常么
Also, I input 3W data packets into the pcap package, and the CSV file exported by cicflowmeter only integrates 1745 traffic features. Is this normal？

**Comment by yorhaha** [comment]
这是正常的，如果你阅读代码的话就会发现，它将属于同一个连接的packet聚合到了一起

**Comment by weinaGWU** [comment]
不好意思， 请问一个很笨的问题， 你install是win10？ 如果是可不可以教一下怎么install？ cmd window 说要java_path.. 多谢

**Comment by yorhaha** [comment]
> 不好意思， 请问一个很笨的问题， 你install是win10？ 如果是可不可以教一下怎么install？ cmd window 说要java_path.. 多谢

不是win10的问题，你应该是没有配置好 java

**Comment by weinaGWU** [comment]
Thank you will check! and will reach back for help.

**Comment by weinaGWU** [comment]
请帮助一下不知道应该JAVA_HOME path set to 什么？ 试了BIN.. 还是说找不到

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
