### ISSUE TITLE
Down/up ratio calculation incorrect

### ISSUE THREAD

**Issue by lisa-lthorrold** [ahlashkari/CICFlowMeter#125]
`if(this.forward.size() > 0){
			return (double)(this.backward.size()/this.forward.size());
		}
		return 0;
}`

This is casting the result of an integer division (int/int) [which returns an int] to a float, rather than correctly casting the numerator to force a double to ensure a proper division. The result is that the down/up ratio is always 0 or 1, which I think is unintended (based on the return type).

**Comment by yorhaha** [comment]
If you still pay attention to this project, welcome to refer to my forked repository: 

https://github.com/blueice-thu/CICFlowMeter. 

Your issue has been resolved in my repository. I will improve the project and resolve as many issues as possible recently. Welcome for suggestions. :)

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
