### ISSUE TITLE
Realtime capture won't work

### ISSUE THREAD

**Issue by Panagiss** [ahlashkari/CICFlowMeter#126]
Hi,

I run cicflowmeter with sudo privileges. It is possible to access the interface but it won't capture anything nor will it save something.
![image](https://user-images.githubusercontent.com/56695201/142293926-ba77ece0-a3c9-4e72-ac99-10a3639998d4.png)

Terminal output:
![image](https://user-images.githubusercontent.com/56695201/142294013-a86c0d99-b6fd-4046-a150-efc1eff7f8a1.png)

The paths shown in the terminal don't exist. Because there was nothing captured.
Also to mention that i have changed interfaces and i also have put ```any``` as an option but no luck

**Comment by Chenhait** [comment]
> Hi,
> 
> I run cicflowmeter with sudo privileges. It is possible to access the interface but it won't capture anything nor will it save something. ![image](https://user-images.githubusercontent.com/56695201/142293926-ba77ece0-a3c9-4e72-ac99-10a3639998d4.png)
> 
> Terminal output: ![image](https://user-images.githubusercontent.com/56695201/142294013-a86c0d99-b6fd-4046-a150-efc1eff7f8a1.png)
> 
> The paths shown in the terminal don't exist. Because there was nothing captured. Also to mention that i have changed interfaces and i also have put `any` as an option but no luck

I meet the same problem, did you solve it?

**Comment by Panagiss** [comment]
> > Hi,
> > I run cicflowmeter with sudo privileges. It is possible to access the interface but it won't capture anything nor will it save something. ![image](https://user-images.githubusercontent.com/56695201/142293926-ba77ece0-a3c9-4e72-ac99-10a3639998d4.png)
> > Terminal output: ![image](https://user-images.githubusercontent.com/56695201/142294013-a86c0d99-b6fd-4046-a150-efc1eff7f8a1.png)
> > The paths shown in the terminal don't exist. Because there was nothing captured. Also to mention that i have changed interfaces and i also have put `any` as an option but no luck
> 
> I meet the same problem, did you solve it?

No !
It's sad to see that it's almost broken... Both the Java version and the python version of the tool. 
As a workaround I just used the tool only as a feature extraction tool from pcap files that i have already captured. It doesn't work as packet capture tool at all...

**Comment by Chenhait** [comment]
> 

thank you so much for your information

**Comment by Chenhait** [comment]
> > > Hi,
> > > I run cicflowmeter with sudo privileges. It is possible to access the interface but it won't capture anything nor will it save something. ![image](https://user-images.githubusercontent.com/56695201/142293926-ba77ece0-a3c9-4e72-ac99-10a3639998d4.png)
> > > Terminal output: ![image](https://user-images.githubusercontent.com/56695201/142294013-a86c0d99-b6fd-4046-a150-efc1eff7f8a1.png)
> > > The paths shown in the terminal don't exist. Because there was nothing captured. Also to mention that i have changed interfaces and i also have put `any` as an option but no luck
> > 
> > 
> > I meet the same problem, did you solve it?
> 
> No ! It's sad to see that it's almost broken... Both the Java version and the python version of the tool. As a workaround I just used the tool only as a feature extraction tool from pcap files that i have already captured. It doesn't work as packet capture tool at all...

thank you so much for your information

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
