### ISSUE TITLE
Could not determine java version from '11.0.11'.

### ISSUE THREAD

**Issue by Chenhait** [ahlashkari/CICFlowMeter#127]
when i try 
./gradlew execute
there is a bug
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine java version from '11.0.11'.

thank you so much if any advance!
best

**Comment by georgemary3311** [comment]
try Java 8

**Comment by 0neday** [comment]
fix?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
