### ISSUE TITLE
PSH Flag Count and URG Flag Count always 0

### ISSUE THREAD

**Issue by lexiea** [ahlashkari/CICFlowMeter#129]
`PSH Flag Count` and `URG Flag Count` are always equal to 0. Also, I could see at least for `PSH Flag Count`, 
`Fwd PSH flags` + `Fwd PSH flags` != `PSH Flag Count`.

I believe I have found the problem: in `BasicPacketInfo.java`  in the function `public void firstPacket(BasicPacketInfo packet){...}` the Fwd and Bwd counts are incremented like this: 

```
if(packet.hasFlagPSH()){
	this.fPSH_cnt++;
}
if(packet.hasFlagURG()){
	this.fURG_cnt++;
```
However, this same incrementation is missing in the function `public void addPacket(BasicPacketInfo packet){...}` (in the same file) and therefore, only the flags of the first packet are counted towards the `Fwd PSH flags` and `Fwd PSH flags` values.

**Comment by yorhaha** [comment]
If you still pay attention to this project, welcome to refer to my forked repository: 

https://github.com/blueice-thu/CICFlowMeter. 

Your issue has been resolved in my repository. I will improve the project and resolve as many issues as possible recently. Welcome for suggestions. :)

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
