### ISSUE TITLE
Load Button doesn't do anything

### ISSUE THREAD

**Issue by 0x00nier** [ahlashkari/CICFlowMeter#130]
On running "gradlew execute" on Windows, the "Load" button does nothing at all. I even ran the command "gradlew execute" on a Command Prompt with Administrator Privileges.

**Comment by thomasreilly1011** [comment]
I had a similar issue just recently running CICFlowMeter on windows. I solved it by following the RELEASE_NOTES.txt file in jnetpcap\win\jnetpcap-1.4.r1425 and installing winpcap. The website it points you to (www.winpcap.org) seems to be down at the time of writing this but I found a download on Softonic https://winpcap.en.softonic.com/. I also had to restart my machine before it started working. Hope this works for you!

**Comment by 0x00nier** [comment]
I see. I have tried the tool both with Npcap and Winpcap but it didn't seem to work. However, I was able to use the GUI in a new virtual machine based on Windows 7. This is quite odd but I think the problem lies with the enumeration of network devices while running the GUI but I don't know how to fix that. It seems like a case-specific problem in my case but there is nothing irregular in my setup of network adapters and whatnot.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
