### ISSUE TITLE
load button for load network interfaces

### ISSUE THREAD

**Issue by simosimo88** [ahlashkari/CICFlowMeter#133]
On running "gradlew execute" on Ubuntu, the "Load" button does nothing at all. I even ran the command "gradlew execute" on a Bash with Administrator Privileges.

![Image1](https://user-images.githubusercontent.com/57046056/152673815-6d4a2a55-dec4-4587-a315-7b29019f35e9.png)

**Comment by ekky-kharismadhany** [comment]
Do you have ```libpcap-dev``` package installed on your machine?
If you don't, you can install it with ```sudo apt install libpcap-dev```

**Comment by finloop** [comment]
> If you don't, you can install it with sudo apt install libpcap-dev

That worked for me on PopOS 22.04. Thanks!

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
