### ISSUE TITLE
What's the difference between packet length and packet size

### ISSUE THREAD

**Issue by KaiyiZhang0929** [ahlashkari/CICFlowMeter#135]
I am confused about the difference between the two features.

Packet Length Mean:		Mean length of a packet
Average Packet Size:		Average size of packet

Can you please clarify the difference?

**Comment by KaiyiZhang0929** [comment]
![1646061059(1)](https://user-images.githubusercontent.com/45109782/156007280-de65c488-77b9-4071-b331-b5c8b3f8b65a.png)
The method of getting Packet Length Mean:
![7cf8cb65ade0d8c67bb6155ee24980d](https://user-images.githubusercontent.com/45109782/156007726-f19df8c8-5138-49ff-9fe3-b080868211f8.png)
The method of getting Average Packet Size:
![5060fff8a428faf1519268db7388a86](https://user-images.githubusercontent.com/45109782/156007744-507117f7-a2e2-41d6-b9d2-95efd8ad264f.png)

I check your code, it looks like you add the payloadBytes of **the first packet** to flowLengthStats twice.
I suspect it is incorrect. Can you please clarify it?

**Comment by yorhaha** [comment]
If you still pay attention to this project, welcome to refer to my forked repository: 

https://github.com/blueice-thu/CICFlowMeter. 

Your issue has been resolved in my repository. I will improve the project and resolve as many issues as possible recently. Welcome for suggestions. :)

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/

**Comment by Vakaloo** [comment]
I am, also, confused about the difference between those two features. I can understand that they are calculated differently what is the actual difference? Thank you!
