### ISSUE TITLE
Getting an error while installing CICFlowmeter

### ISSUE THREAD

**Issue by meenakshi510** [ahlashkari/CICFlowMeter#137]
FAILURE: Build failed with an exception.

*What went wrong:
Could not determine Java version from '13.0.7'.

*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug

**Comment by manush1729** [comment]
> FAILURE: Build failed with an exception.
> 
> *What went wrong: Could not determine Java version from '13.0.7'.
> 
> *Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug

Even i get the same error

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
