### ISSUE TITLE
Can the tool delete some features and keep some features

### ISSUE THREAD

**Issue by banzhuanle** [ahlashkari/CICFlowMeter#138]
For some network attack traffic, some characteristics are unnecessary and time-consuming to calculate. May I ask in which files I should delete them and retain some of the features?

**Comment by ltkhang** [comment]
all of the variables are statistical variables and they are deduced by each other. so you have only 1 option that dives deep into the code and delete the code calculating them and delete their outcomes in the report exporting function

**Comment by zlovec2012** [comment]
change code in cic/cs/unb/ca/jnetpcap/BasicFlow.java.FlowBasedFeaturesEx()

**Comment by mohammadelhaj** [comment]
@banzhuanle , @ltkhang , @zlovec2012 can someone help me run cicflowmeter please

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
