### ISSUE TITLE
CICFlowMete problem

### ISSUE THREAD

**Issue by mashaleh75** [ahlashkari/CICFlowMeter#139]
Hi,
This is my first attempt at running CICFlowMete on pcaps.

When I select the input pcap file, the output directory, the logger pane shows a message "CICFlowMeter has received 1 pcap file" and then nothing happens. no output 

?
![Capture](https://user-images.githubusercontent.com/89278040/164985557-d95e7578-8d85-4b8b-ba6c-1abcb5ba0fb6.JPG)

**Comment by mashaleh75** [comment]
any help

**Comment by mashaleh75** [comment]
:(

**Comment by ltkhang** [comment]
try to run under administration

**Comment by abmnyuiwari** [comment]
> try to run under administration

i already try this way but still got the same problem :/ 
i try on windows and ubuntu

**Comment by souravs17031999** [comment]
@ltkhang @abmnyuiwari did you solved this issue ?

**Comment by abmnyuiwari** [comment]
> @ltkhang @abmnyuiwari did you solved this issue ?

no  i dont

**Comment by souravs17031999** [comment]
@abmnyuiwari do you know any other tools that can be used for feature extraction ?

**Comment by abmnyuiwari** [comment]
> @abmnyuiwari do you know any other tools that can be used for feature extraction ?

im using argus tool for feature extraction

**Comment by souravs17031999** [comment]
@abmnyuiwari will the features be helpful in training machine learning models ? Any links could be helpful. 
thanks

**Comment by abmnyuiwari** [comment]
> @abmnyuiwari will the features be helpful in training machine learning models ? Any links could be helpful. thanks

You can install the Argus tool in Linux using the terminal, then for feature extraction, you can customize it according to your needs, for the commands, you can access the following link : https://www.mankier.com/1/ra

**Comment by thetinshusasi** [comment]
Did anyone solved this problem

**Comment by hessammohammadian** [comment]
If you don't receive any output probably the problem is from your pcap file. If the pcap files don't have an ethernet layer the CICFlowmeter can't detect any flows. You need to add the ethernet layer to all pcap files, and it will work.
tcprewrite --dlt=enet --infile="" --outfile=""
