### ISSUE TITLE
How to instal CICFlowGenerator?

### ISSUE THREAD

**Issue by MichaelaFell** [ahlashkari/CICFlowMeter#14]
Hi, 

I want to use CICFlowGenerator and generate som data, but I can't find some information about this feature. Can you help me and give me some information how can I install it?

**Comment by ahlashkari** [comment]
Pls read the README file:
https://github.com/ISCX/CICFlowMeter/blob/master/README.md

**Comment by faiznjust** [comment]
can we run the code on win? as in Readme file it shows for linux

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
