### ISSUE TITLE
Getting actual packet length instead of captured packet length on CICflowmeter

### ISSUE THREAD

**Issue by Sehan234** [ahlashkari/CICFlowMeter#141]
Hi,

I have a pcap with packets captured at a constant length. But their actual packet size varies. This is clearly seen on the 'packets on wire' comment in pcap.

But when I convert the pcap into flows using CICflowmeter, only the captured packet length is taken which is a constant value. Is there any way I can get the actual packet length for the flows by changing the python code? If anyone has done that please advise me.

Thank you
Sehan

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
