### ISSUE TITLE
Issue Converting UNSW-NB15 pcap to CSV file

### ISSUE THREAD

**Issue by adendogar** [ahlashkari/CICFlowMeter#142]
I am using CICIFlowMeter for Converting [UNSW-NB15 Dataset pcaps](https://research.unsw.edu.au/projects/unsw-nb15-dataset) to CSV files . but it’s just generating an empty CSV with zero values. 
![Screenshot 2022-06-20 101120](https://user-images.githubusercontent.com/78276661/174623721-0ae013f4-00cc-49d1-bc46-a28b0c4b3aeb.jpg)
![Screenshot 2022-06-20 101238](https://user-images.githubusercontent.com/78276661/174623725-a0493566-df73-4647-8bd5-26395d284117.jpg)
But working fine for the other Dataset [IOT NETWORK INTRUSION DATASET](https://ieee-dataport.org/zopen-access/iot-network-intrusion-dataset) it convert to the CSV. 
![Screenshot 2022-06-20 101411](https://user-images.githubusercontent.com/78276661/174623775-def5033e-5447-4d4d-9ddf-1c56ebb2bd89.jpg)
![Screenshot 2022-06-20 101505](https://user-images.githubusercontent.com/78276661/174623779-3a588420-0a25-4e73-8c04-3922f6192560.jpg)
I have attached the screenshots as well 

 Can you please suggest something that will be helpful?

**Comment by souravs17031999** [comment]
@adendogar did you solved this issue ?

**Comment by adendogar** [comment]
No

**Comment by Sabari-E** [comment]
Did you find the problem? I trying to convert a pcap recorded in cooja contiki software and it has the same problem. Any help is much appreciated.

**Comment by hessammohammadian** [comment]
The problem is not the CICFlowmeter. It's from the UNSW itself. UNSW pcap files don't have an actual ethernet layer and that's why CICFlowmeter can't detect any flows. You need to add the ethernet layer to all pcap files and then it's going to work.
tcprewrite --dlt=enet --infile="" --outfile=""

**Comment by Sabari-E** [comment]
> The problem is not the CICFlowmeter. It's from the UNSW itself. UNSW pcap files don't have an actual ethernet layer and that's why CICFlowmeter can't detect any flows. You need to add the ethernet layer to all pcap files and then it's going to work. tcprewrite --dlt=enet --infile="" --outfile=""

Can you explain how to add the ethernet layer to pcap files? What is the tcpwrite line command mentioned above? 
Please answer

**Comment by Tyler-ytr** [comment]
Hello! Do you still have the pcap for UNSW_NB15 please? There is no way to download it from the official website

**Comment by TaoChenStu** [comment]
> > 问题不在于 CICFlowmeter。它来自新南威尔士大学本身。新南威尔士大学 pcap 文件没有实际的以太网层，这就是 CICFlowmeter 无法检测到任何流量的原因。您需要将以太网层添加到所有 pcap 文件中，然后它就可以工作了。tcprewrite --dlt=enet --infile=“” --outfile=“”
> 
> 您能解释一下如何将以太网层添加到 pcap 文件中吗？上面提到的 tcpwrite line 命令是什么？请回答

Have you solved the problem?

**Comment by TaoChenStu** [comment]
> > 问题不在于 CICFlowmeter。它来自新南威尔士大学本身。新南威尔士大学 pcap 文件没有实际的以太网层，这就是 CICFlowmeter 无法检测到任何流量的原因。您需要将以太网层添加到所有 pcap 文件中，然后它就可以工作了。tcprewrite --dlt=enet --infile=“” --outfile=“”
> 
> 您能解释一下如何将以太网层添加到 pcap 文件中吗？上面提到的 tcpwrite line 命令是什么？请回答

Have you solved the problem?

**Comment by CahillLJQ** [comment]
@adendogar @Sabari-E Did you solved this issue? I have the same problem.

**Comment by TaoChenStu** [comment]
> The problem is not the CICFlowmeter. It's from the UNSW itself. UNSW pcap files don't have an actual ethernet layer and that's why CICFlowmeter can't detect any flows. You need to add the ethernet layer to all pcap files and then it's going to work. tcprewrite --dlt=enet --infile="" --outfile=""

We successfully processed the UNSW-NB15 dataset using the CICflowmeter tool. However, our current problem is that for the raw pacp form of data, after processing with the CICflowmeter tool, the resulting csv file does not have labels. May I ask how to mark each part of the original pacp data provided by the official website after processing with CICflowmeter?

**Comment by Pranavneupane101** [comment]
> > The problem is not the CICFlowmeter. It's from the UNSW itself. UNSW pcap files don't have an actual ethernet layer and that's why CICFlowmeter can't detect any flows. You need to add the ethernet layer to all pcap files and then it's going to work. tcprewrite --dlt=enet --infile="" --outfile=""
> 
> We successfully processed the UNSW-NB15 dataset using the CICflowmeter tool. However, our current problem is that for the raw pacp form of data, after processing with the CICflowmeter tool, the resulting csv file does not have labels. May I ask how to mark each part of the original pacp data provided by the official website after processing with CICflowmeter?

can you guide me? CICFlowmeter is not capturing the packetflow
