### ISSUE TITLE
Purpose of forward check in BasicPacketInfo. generateFlowId()?

### ISSUE THREAD

**Issue by lisa-lthorrold** [ahlashkari/CICFlowMeter#143]
I can't understand what the purpose of this check is, or in actual fact what is actually being checked. How is the direction determined based solely on ips without context/history, or is the variable name misleading. It results in flowids which are inconsistent with actual src and dest ips features and the calculated features in BasicFlow.java which handles directionality.

Or perhaps, could you clarify if or what semantic directionality intended is for a flowid, or whether the function is to ensure the flowids are generated in a consistent manner (in which case the variable name forward is quite misleading)

I haven't vetted thoroughly but this could impact methods that determine flow existence/directionality based on the flowids

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
