### ISSUE TITLE
Load button doesn't work on  macOS Montery

### ISSUE THREAD

**Issue by redheadedmut** [ahlashkari/CICFlowMeter#148]
I've sucessfully installed & run CICFlowMeter, but the load button doesn't provide any network interfaces. I'm not getting any errors that I can see. My first assumption is that this was due to Mac requiring the user to run an application as admin to capture network packets, but it still doesn't work even after elevating the terminal to super user before running ./gradle execute

**Comment by xyfhappy** [comment]
Hey, bro, this is the exact problem occured to me. However my operate system is windows. Did you solve this problem?

**Comment by mohammadelhaj** [comment]
@yzyhappy, @redheadedmut   hello bro i have the same problem how did you fix it?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
