### ISSUE TITLE
Load Network Device Button

### ISSUE THREAD

**Issue by constant5** [ahlashkari/CICFlowMeter#15]
On linux install: when pressing the "load" button, nothing happens.

**Comment by ahlashkari** [comment]
If you install it completely, it will show the list of network interfaces on your machine in the below box and you can select any of them for the next step.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
