### ISSUE TITLE
install cicflowmeter on win10

### ISSUE THREAD

**Issue by weinaGWU** [ahlashkari/CICFlowMeter#150]
I have downloaded and extracted the cicflowmeter-4.0 on my win 10 / 11 machine. 
From the cmd window, when I try to load the cicflowmeter.bat under bin, it says JAVA_HOME is not set and no Java command could be found in my PATH. I am not a programmer, need to convert a PCAP file to CSV by using CICFLOWMETER. maybe a very dumb question, can someone help me complete the install (any step by step on what I am missing) would be greatly appreciated.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
