### ISSUE TITLE
Slow to convert a big file?

### ISSUE THREAD

**Issue by raikone14** [ahlashkari/CICFlowMeter#151]
Hey,
I am converting a big capture 2.5 gb to dataset, and already took me 2 days and is not over yet, should be that slow?
there is anything that I can do?
I am doing this way
sudo cicflowmeter -f datast_final2.pcap  -c mydata.csv
Thank you

**Comment by souravs17031999** [comment]
@raikone14 can you tell me how are you running this command ? It says ```cicflowmeter``` not found. 
Am I missing something ?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
