### ISSUE TITLE
Time unit for the fields "Flow Timeout" and "Activity Timeout"

### ISSUE THREAD

**Issue by leonardohdemelo** [ahlashkari/CICFlowMeter#152]
I would like to know what is the time unit of the "Flow Timeout" and "Activity Timeout" fields. When reading a code snippet, it was possible to identify that the unit is microseconds for the flow, so I considered this unit for these fields as well. Could you confirm if the unit for these fields is microseconds?

I leave the suggestion for a small implementation to add the unit of the field in the text of the label.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
