### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by souravs17031999** [ahlashkari/CICFlowMeter#154]
Hi @ahlashkari , Should this project be still used considering many bugs reported and still opened in issues ? Or is it outdated/deprecated/not maintained ? It will be great if you could update the project status.

**Comment by southwestflavorz** [comment]
I'm wondering the same thing myself. Doesn't seem to be very active.

**Comment by ahlashkari** [comment]
Hi @souravs17031999  and @southwestflavorz,
As you know, this is the nature of open-source projects. An open-source project should not die, as it is an idea that has been released by someone one day, and the others have the chance to improve or enhance it. As you can see, there are so many versions of this project, each covering one or more issues. You can work and improve it if you want also. 
BTW, as this project was designed in 2015 using Java, on some parts, it is not possible to improve or handle the issue(s), so I decided to release a new version using Python, which most of the fundamental problems have been covered there. I hope the R&D team can release the new one by the end of this year. But, still, it does not mean that this version will not be helpful in the future for exceptional cases and situations.

**Comment by Jumabek** [comment]
Prof @ahlashkari 
this is awesome project, thank you

which python version are you referring to? link pls?

**Comment by ahlashkari** [comment]
Hi @Jumabek,
As I mentioned, it will be released by the end of this year.
