### ISSUE TITLE
CICFlowMeter gives wrong output

### ISSUE THREAD

**Issue by mizan8501** [ahlashkari/CICFlowMeter#156]
Hi, I have collected pcap files using tcpdump. After extracting data using offline mode, I find it gives wrong IP addresses, 0 for source port, destination port, and protocol. If I open Pcaps using wireshark, I can see all IP addresses are present whereas CICFlowmeter shows completely different IPs. I am also confused regarding other outputs as well

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
