### ISSUE TITLE
Empty CSV generated

### ISSUE THREAD

**Issue by Sabari-E** [ahlashkari/CICFlowMeter#158]
I have a pcap file generated in cooja contiki simulation of RPL networks. On using cicflowmeter an empty csv file is generated. I have attached the files here. 
In previous closed issues it was suggested to add ethernet layer using tcprewrite. I used editcap of wireshark instead and included ethernet layer.
![RPLtopology1m1](https://user-images.githubusercontent.com/113427141/230718415-b0d8deff-9a39-4752-9170-843fdb80c6bf.jpg)
I have attached both the original and modified pcap file here.
[RPL PCAP files-20230408T112237Z-001.zip](https://github.com/ahlashkari/CICFlowMeter/files/11183095/RPL.PCAP.files-20230408T112237Z-001.zip)
Even after converting the problem persists.
![cicflow](https://user-images.githubusercontent.com/113427141/230718589-2c55535d-b2f2-4967-8ed2-6b1f86fdc352.jpg)

Can you look into it and provide solution at the earliest?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
