### ISSUE TITLE
How features are grouped. Pkt/s, frames/s, Bytes/s or other?

### ISSUE THREAD

**Issue by luizpatrocinio** [ahlashkari/CICFlowMeter#162]
Hello everything is fine?

How does CicFlowMeter group by source IP? What is the scale to form a metric of the characteristics. Is it a grouping by time? By Frames. If it's by time, tell me how many seconds, if it's by frames, tell me how many frames are expected to perform the computation, if it's by packets, how many packets are expected? Thanks.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
