### ISSUE TITLE
Load button doesn't load the interfaces in Windows 11

### ISSUE THREAD

**Issue by bvargas91** [ahlashkari/CICFlowMeter#166]
Your help please for checking which can be the problem, I have 1.8.0_341 Java version, Windows 11.

Thanks
Regards

**Comment by ahlashkari** [comment]
Hi, 
I am suggesting to use the Python version of the project with more features and functionality, available here: 

https://github.com/ahlashkari/NTLFlowLyzer

Good luck.

**Comment by bvargas91** [comment]
Hello, I want to use the CICIDS 2017 or 2018 Dataset for a project, these datasets were captured with CICflowmeter. My question is If I can use this new program NTLFlowLyzer for capturing traffic on real time, because it has more attributes.

Thanks!

**Comment by bvargas91** [comment]
Hello, I want to use the CICIDS 2017 or 2018 Dataset for a project of malware detection, these datasets were captured with CICflowmeter. My question is If I can use this new program NTLFlowLyzer for capturing traffic on real time, because it has more attributes.

Thanks!
