### ISSUE TITLE
Can i use CICFlowMeter to convert PCAP -> XML? Where is manual?

### ISSUE THREAD

**Issue by CapSparkle** [ahlashkari/CICFlowMeter#17]
I can't find manual to this utility. Where can i find it? Thank you in advance.

**Comment by ahlashkari** [comment]
Pls read the ReadMe.Md file.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
