### ISSUE TITLE
Could not find org.jnetpcap:jnetpcap:1.4.1.

### ISSUE THREAD

**Issue by picohub** [ahlashkari/CICFlowMeter#19]
I get this error:
Could not find org.jnetpcap:jnetpcap:1.4.1.

**Comment by picohub** [comment]
Solved by this change in build.gradle file:
    compile group: 'jnetpcap', name: 'jnetpcap', version:'1.4.r1425-1g'

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
