### ISSUE TITLE
More than 100mb

### ISSUE THREAD

**Issue by picohub** [ahlashkari/CICFlowMeter#20]
Why did you put a 100mb limit? and how can i remove this?

**Comment by ahlashkari** [comment]
Bcs it is the academic version of the FlowMeter. You can change the code to accept several portions of the networ traffic and merge the results.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
