### ISSUE TITLE
CIC-IDS-2017 - Init_win_bytes_forward = '-1'

### ISSUE THREAD

**Issue by PalGiupo** [ahlashkari/CICFlowMeter#21]
Why the number of bytes of first packet send is '-1' in almost all entry in the Wednesday Dos Dataset?
Other fields also have this value. It makes it impossible for me to apply many algorithms, if not replacing these values ​​with '1', but is it correct? The number of bytes of the first request packet is impossible to be zero. I would need to have the number of bytes of the first packet sent, in order to recognize portscanning and bruteforce attacks

**Comment by ahlashkari** [comment]
You can normalize your data for the specific algorithm by changing the -1 to 0 or 1. 
For the number of bytes in the first packet, you need to add a function there as we are not caculating it.

**Comment by sebitas0623** [comment]
Hi ahlashkari

I would like to know what is the meaning of  -1 value in this feature. thank you.

**Comment by ahlashkari** [comment]
Hi, we already change all of them to "0" as default, but it was because of our previous project and normalization section that we need that number.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
