### ISSUE TITLE
How flow direction of a packet is determined?

### ISSUE THREAD

**Issue by Jumabek** [ahlashkari/CICFlowMeter#23]
Hi,

FLOWMETER is generating FlowId with below source:

```
public String generateFlowId(){
    	boolean forward = true;
    	
    	for(int i=0; i<this.src.length;i++){           
    		if(((Byte)(this.src[i])).intValue() != ((Byte)(this.dst[i])).intValue()){
    			if(((Byte)(this.src[i])).intValue() >((Byte)(this.dst[i])).intValue()){
    				forward = false;
    			}
    			i=this.src.length;
    		}
    	}     	
    	
        if(forward){
            this.flowId = this.getSourceIP() + "-" + this.getDestinationIP() + "-" + this.srcPort  + "-" + this.dstPort  + "-" + this.protocol;
        }else{
            this.flowId = this.getDestinationIP() + "-" + this.getSourceIP() + "-" + this.dstPort  + "-" + this.srcPort  + "-" + this.protocol;
        }
        return this.flowId;
    }

```
What code says is "If src_ip of the packet is small then it is FWD packet, otherwise it is BWD packet"

[Code refernce](https://github.com/ISCX/CICFlowMeter/blob/master/src/main/java/cic/cs/unb/ca/jnetpcap/BasicPacketInfo.java#L52)

However, the  [netflowmeter page](http://www.netflowmeter.ca/netflowmeter.html) says
Flow direction is determined when first packet of the flow arrives.

It seems to me above two contradicts each other.
Would you kindly explain more how generateFlowId() method is determining direction and generating flowid?

**Comment by ahlashkari** [comment]
Thanks, Jumabek. 
As you can see here we assumed that the sender has a local IP and receiver has a public and external IP which could be a problem for some type of communications. BTW, we realized a few problems in our package which is one of them and hope we will cover them in the next version.

**Comment by ahlashkari** [comment]
Pls, check the new version now which is based on the original definition.

**Comment by KaiyiZhang0929** [comment]
it looks like this problem for the new version still exists...

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
