### ISSUE TITLE
no feature labels on each feature columns

### ISSUE THREAD

**Issue by faiznjust** [ahlashkari/CICFlowMeter#28]
hi,
i executed CICFlowmeter, when i run the GUI (APP.JAVA) file, it give correct output CSV file with features but when i run the CICFLOWMETER.java file and give path to input pcap files and output folder, it generates flows but the feature labels are missing. you can check from the screnshots here;
![6a9f29bcc73075d84831c8ac851fa4a](https://user-images.githubusercontent.com/39428386/59735450-31c96300-9288-11e9-970b-f109de42b166.png)
![9707b0931e3522a6f48d7b2f92ded2a](https://user-images.githubusercontent.com/39428386/59735453-34c45380-9288-11e9-9858-6964b3f094cc.png)

**Comment by psychogyiokostas** [comment]
hello @faiznjust 

Did you fix this?

I have similar issue:

https://github.com/ahlashkari/CICFlowMeter/issues/42

**Comment by faiznjust** [comment]
> hello @faiznjust
> 
> Did you fix this?
> 
> I have similar issue:
> 
> #42

dear you have to label manually or write any label name instead of "No Label" in source code.
thanks

**Comment by ahlashkari** [comment]
Hi,
Thanks for your attention. Pls, download the new version of the FlowGenerator.Java file from the JnetPcap folder.

**Comment by ahlashkari** [comment]
Hi,
Thanks for your attention. If you are asking for the **Flow Label** (the last cell of each flow), you need to change it manually and based on the flow first 5 features including SourceIP, DestinationIP, SourcePort, DestinationPort, TimeStamp, and Protocol. 
If you are aksing about the **header** of the columns which are the feature names, you can download the new version of the FlowGenerator.java from JnetPcap now.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
