### ISSUE TITLE
pom.xml seems forget tika dependecy

### ISSUE THREAD

**Issue by b04505009** [ahlashkari/CICFlowMeter#3]
pom.xml seems forget tika dependecy

**Comment by ahlashkari** [comment]
Hi,
Pls use the CICFlowMeter as the ISCXFlowmeter is out of date now.

**Comment by b04505009** [comment]
Is this not CICFlowMeter ?

**Comment by ahlashkari** [comment]
Yes, your previous comment appeared at ISCXFlowmeter. But, this is right. Do you have issue here?

**Comment by b04505009** [comment]
Yes. When I imported this project to intellij idea by maven, it reported that there was no tika dependency. So I add it into pom.xml.

Another question, can CICFlowMeter read .pcapng files?

**Comment by ahlashkari** [comment]
Thanks. 
We already updated the pom.xml now. Also, it can not read the pcappng but you can convert it to pcap and feed to the application.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
