### ISSUE TITLE
I upload the pcap file,and click 'ok' button, it shows Error while opening file for capture: bad dump file format

### ISSUE THREAD

**Issue by superjdz** [ahlashkari/CICFlowMeter#30]
![image](https://user-images.githubusercontent.com/36131558/60641691-7267d580-9e5f-11e9-9cc6-4d50d79f8b6f.png)

when i click the 'ok' button, it shows the Error above.

this file was processed by
![image](https://user-images.githubusercontent.com/36131558/60641630-30d72a80-9e5f-11e9-9806-857d30b41405.png)

 and the size of the file I used is 19.8M
MondayWorkingHours.pcap is one of the file provided by CICIDS2017 dataset

Thank you for helping me!

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
