### ISSUE TITLE
Discrepancies between offline and online flow packet reader

### ISSUE THREAD

**Issue by PoisonousMushroom** [ahlashkari/CICFlowMeter#31]
I suspected something might be off with the offline packet reader so I did a test to try it. I was on one side reading all my traffic live with pyshark and then saving it to a pcap file and on the other, I was reading the traffic flows live. Now on the live version, I get 36 flows whereas when I run the offline version on the same traffic I get 0 flows. what could this be?

![image](https://user-images.githubusercontent.com/25646367/60808207-fc79ac00-a187-11e9-83d5-d74e6d4ddde2.png)
 note that the 1 flow it says it returns are in fact just the names of the fields

**Comment by ahlashkari** [comment]
Hi,
Pls, read the related document and published papers. CICFlowMeter will meter the TCP and UDP packets, not the others. Also, there are several conditions for making the complete flow such as minimum time window which maybe you don't have in other software.
