### ISSUE TITLE
CICFlowMeter generating empty CSV files with 0 flows

### ISSUE THREAD

**Issue by LRSAnnaba** [ahlashkari/CICFlowMeter#32]
Hi, 
I tried executing the jar, as well as from Eclipse, and in both cases I face the following issue: The generated CSV file is empty with 1.1 Ko 
I have tested CIC flowmeter with other PCAP files and it worked fine.

Please advise

**Comment by ahlashkari** [comment]
Hi,
It shows there are some issues in your PCAP file, otherwise, it should work.

**Comment by souravs17031999** [comment]
@ahlashkari I am having same issues , please help.
