### ISSUE TITLE
How to develop using tensorflow(1.14)

### ISSUE THREAD

**Issue by Riitt** [ahlashkari/CICFlowMeter#33]
How to  develop this using Tensorflow 1.13/1.14  for CICFlowmwter

https://cse-cic-ids2018.s3.ca-central-1.amazonaws.com/Processed+Traffic+Data+for+ML+Algorithms/Friday-02-03-2018_TrafficForML_CICFlowMeter.csv

I am new to this area 

@Jumabek

**Comment by Riitt** [comment]
@Jumabek

can you help for this using tensorflow

**Comment by Jumabek** [comment]
Hi unfortunately i changed my direction. So i do not have ecperience to
help you. I recommend checking out tensorflow tutorials on rrn

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
