### ISSUE TITLE
A suggestion on the part to install jnetpcap

### ISSUE THREAD

**Issue by jeongmincha** [ahlashkari/CICFlowMeter#34]
I don't think it is a big deal, but it would be helpful for beginners of your repository.

Your README is saying
```
//windows: at the pathtoproject/jnetpcap/win/jnetpcap-1.4.r1425
mvn install:install-file -Dfile=jnetpcap.jar -DgroupId=org.jnetpcap -DartifactId=jnetpcap -Dversion=1.4.1 -Dpackaging=jar
```
but, there is no `pom.xml` at the specified path (pathtoproject/jnetpcap/win/jnetpcap-1.4.r1425).

So I think it would be better if you write it like below.
```
//windows: at root directory of this repository
mvn install:install-file -Dfile=".\jnetpcap\win\jnetpcap-1.4.r1425\jnetpcap.jar" -DgroupId="org.jnetpcap" -DartifactId=jnetpcap -Dversion="1.4.1" -Dpackaging=jar
```
Windows cmd cannot recognize the complex path and strings containing ".", so I think it would be better to use quotation marks on them.

Thanks.

**Comment by ahlashkari** [comment]
Thanks, Jeongmincha.

**Comment by UserXSX** [comment]
Thank you. This problem has troubled me for a day.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
