### ISSUE TITLE
Does it have CLI version?

### ISSUE THREAD

**Issue by RyuAsuka** [ahlashkari/CICFlowMeter#36]
Does it only have GUI version? I want to run it in pure CLI environment... How should I do?

**Comment by RyuAsuka** [comment]
Oh, I found it. The cfm program is the CLI version. I suggest the developers write it clearly in the readme file please.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
