### ISSUE TITLE
Partial Flows in the final CSV

### ISSUE THREAD

**Issue by HarishNe** [ahlashkari/CICFlowMeter#38]
CSV generated has flow entries with same ID, and few flows has Flow Duration == 0 micro seconds. 
     By default flow timeout is set to 120 sec, and few discussion I read it should be 600  seconds. Please suggest me what should be the idle flow timeout and activity timeout.
    Is the timeout set in the code affecting in number of flows being generated.
    what should be the SYN and FIN flag count in an idle flow?

**Comment by ahlashkari** [comment]
Hi, Timeout is a variable and you can change it based on your research results either 120 or 600. 
For the flags' counter, pls download the update code on last week. The value of the flags is based on the related bit in the header of the packet and the FlowMeter just counts the number of "1" values there.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
