### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by harik68** [ahlashkari/CICFlowMeter#4]
Hi, I was trying to install CICFlowMeter but facing the following problems:

Step 1: Extract CICFlowMeterV3.zip. The file available for download from this site is CICFlowMeter-master.zip and not  CICFlowMeterV3.zip

I still downloaded CICFlowMeter-master.zip and extracted

Step 2: Go to the extracted directory, enter the 'bin' folder

No bin folder is found in the extracted directory CICFlowMeter-master

Please fix the issue or let me know how to install from other sources.

Thanks and Regards,
-Hari

**Comment by ahlashkari** [comment]
Hi Hari,
Thanks for the point that you mentioned. As the .zip package is not for the Github, please let's to contact directly on my email a.habibi.l@unb.ca and I will help you directly.

**Comment by ahlashkari** [comment]
You can download the CICFlowMeterV3.zip from this web-page:
http://www.unb.ca/cic/research/applications.html#CICFlowMeter
It already highlighted as "Jar Package".

**Comment by faiznjust** [comment]
Sir,
i also download CICFlowmeter-V4.0. i didn't find any 'bin' folder. Could you please help me out via email. thanks

**Comment by tirth-cloudops** [comment]
@ahlashkari  the source file is missing in the link you provided. Kindly check the link. Sorry if I am missing something in the docs.

**Comment by tirth-cloudops** [comment]
@faiznjust Hey if you have a link for cicflowmeterv4 or v3. It would be great if you share it with me. Thanks!!

**Comment by faiznjust** [comment]
> @faiznjust Hey if you have a link for cicflowmeterv4 or v3. It would be great if you share it with me. Thanks!!

https://github.com/ahlashkari/CICFlowMeter    Dear, 
i found all the details here.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
