### ISSUE TITLE
Labels missing from extracted xml

### ISSUE THREAD

**Issue by psychogyiokostas** [ahlashkari/CICFlowMeter#42]
Hello,

Using as input to the ISCX FlowMeter-4.0 the file: testbed-12jun.pcap i get as output the respective flow file.

The issue here is that the output file's feature 'Label' has values None, unlike the xml outputs that you provide in:

http://205.174.165.80/CICDataset/ISCX-IDS-2012/

I can see that you have uploaded the labeled xml outputs , but i am concerned about how to obtain the labeled xml file in first place.

So my question is:
If i use for instance testbed-jun12.pcap from your link with FlowMeter-4.0 i should get labeled flows in xml format? If the raw pcap files do not contain labels, is there a link to the labeled raw pcap files?

Thank you in advance.

**Update:**

I also did this:

1. merged pcap files into one from all 7 days.
2. run merged pcap file with CICFlowMeter-4.0

Again the result is the same as the column "Label" has rows with value: "No Label".

**Comment by psychogyiokostas** [comment]
The ReadMe.txt file includes all 84 extracted features by CICFlowMeter-4.0:

After comparing the features i got by processing my pcap files with CICFlowMeter-4.0, to the features mentioned in the ReadMe i noticed this:

_Features from CICFlowMeter:_

Total: 84
Includes Feature: "Label" with values No Label

_Features reported in ReadMe.txt:_

Total: 84
Do not include "Label" feature, but mention 2 times the same feature: "Fwd Header Length"

Can you please clarify? Thank you.

**Comment by ahlashkari** [comment]
Thanks, Psychogyiokostas,
The "Label" column is for researchers to complete them based on their methodology. FlowMeter can extract the feature but can not label the traffic. I different datasets such as IDS2017 or DDoS2019, we labeled them based on our internal methodology and scenarios. 
For the feature duplication, we will remove it in the next version.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
