### ISSUE TITLE
Missing columns information

### ISSUE THREAD

**Issue by valiente98** [ahlashkari/CICFlowMeter#43]
Hi,

I am using the csv files from the following link: https://www.unb.ca/cic/datasets/ids-2018.html.
As it is explained in 3 - Feature Extraction, the csv files might contain 6 columns (FlowID, SourceIP, DestinationIP, SourcePort, DestinationPort, and Protocol) and other features (about 80). The main problem is that the csv files does not contain the first 6 columns, they just contain destinationPort, protocol and the 80 features.

Also, the protocol column contains a single number between 0 to 17, without knowing which protocol matches that number.

I attached you a single screenshot showing that:

![image](https://user-images.githubusercontent.com/46867005/69533270-68aa5000-0f6f-11ea-8090-d78cca421074.png)

Thanks in advance,

**Comment by ahlashkari** [comment]
Hi, 
We removed the Source IP, Destination IP, and Source Port columns from Dataset as it will affect your training model. 
For the Protocol number, these are the standard numbers and you just need to Google it. 
https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml
BTW, pls ask questions about datasets on the right channel not here, as they are not related to this project.

**Comment by lambders** [comment]
@ahlashkari I'm interested in the version of the IDS 2018 dataset that contains the Source IP, Destination IP, Source Port, Destination Port fields. Do you still have the old version of IDS 2018 hosted anywhere with those columns? Thank you so much!

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
