### ISSUE TITLE
Could you please provide the calculation formula using for the feature extraction?

### ISSUE THREAD

**Issue by jibanli** [ahlashkari/CICFlowMeter#44]
I have some difficult reading the java code. Could you please provide the calculation method in python way?

**Comment by jibanli** [comment]
![bulk_rate](https://user-images.githubusercontent.com/39478794/69705717-0ef18380-1131-11ea-928c-b6aa9de08379.png)

**Comment by jibanli** [comment]
And what means the 'bulk rate'?

**Comment by aouinizied** [comment]
check nfstream python package as it's more suitable for flow based feature computation using Python.

**Comment by ahlashkari** [comment]
Hi @jibanli,
We don't have the formula but you can understand the feature calculation by reading the function of each feature in the source code and related description (We don't have this package in Python). For the Bulk rate that you asked, please read  below webpage to understand the concept:
http://isp.vsi.ru/library/Networking/TCPIPIllustrated/tcp_bulk.htm

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
