### ISSUE TITLE
Possible incorrect calculation of Tot Fwd Pkts and Tot Bwd Pkts

### ISSUE THREAD

**Issue by Jaidip** [ahlashkari/CICFlowMeter#45]
Greetings,

I have noticed that csv generated by the tool have incorrect calculation of Tot Fwd Pkts and Tot Bwd Pkts. "Tot Fwd Pkts" is always one less than actual and  "Tot Bwd Pkts" is always one more than actual. I have cross verified with output of conversations in wireshark. 

Please verify from your end and update the main source code.

Thanks

**Comment by ahlashkari** [comment]
Hi,
Thanks for the feedback. Pls, download the new BasicFlow.Java now.

**Comment by wshwhyu** [comment]
Solve it? What should be done. Could you explain step by step in detail

**Comment by wshwhyu** [comment]
download the new BasicFlow.Java and What to do next？Thanks

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
