### ISSUE TITLE
How linux os use realtime function

### ISSUE THREAD

**Issue by RonnieNiu** [ahlashkari/CICFlowMeter#46]
How linux os use realtime function
![image](https://user-images.githubusercontent.com/21351974/70294665-3a562b80-181f-11ea-9c03-0e10c92161f4.png)

**Comment by RonnieNiu** [comment]
win 10 pro  click load no response
![image](https://user-images.githubusercontent.com/21351974/70294738-6c678d80-181f-11ea-9af1-5876c1f4dc68.png)

**Comment by Msivachaithanyaprasad** [comment]
Same problem can u please help me

**Comment by Logan-Davidson** [comment]
You will need to add the vm arguments that are given in the readme to your run configurations
Here they are:
Djava.library.path="pathtoproject/jnetpcap/linux/jnetpcap-1.4.r1425"

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
