### ISSUE TITLE
What's the difference between flow timeout and activity timeout in offline mode?

### ISSUE THREAD

**Issue by b04505009** [ahlashkari/CICFlowMeter#5]
I guessed flow timeout is for  both TCP and UDP, is that right?

**Comment by b04505009** [comment]
Oh, is activity timeout used to calculate idle feature?

**Comment by 5225507** [comment]
Unfortunately, these options are very confusing.
I searched the internet but could not find anything.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
