### ISSUE TITLE
How to open CIC flow meter in whonix workstation

### ISSUE THREAD

**Issue by Msivachaithanyaprasad** [ahlashkari/CICFlowMeter#50]
The below link contains my error please respond sir.
[https://github.com/ahlashkari/CICFlowMeter/pull/48#issuecomment-579243408](url)

**Comment by ahlashkari** [comment]
CICFlowMeter has been configured for Ubuntu and Windows at this moment.

**Comment by Msivachaithanyaprasad** [comment]
So, I can't able to capture the data via whonix workstation with CIC flow meter?
What is another way to capture the tor or non-tor data (.pcap file) can u please help me!

**Comment by Msivachaithanyaprasad** [comment]
Thank u for your response, sir.
Hai sir,
If CIC flow meter is only configured with ubuntu and windows then how can I
capture the tor or nontor data (.pacap files) in virtual box in whonix (is
a Debian GNU/Linux–based security-focused Linux distribution).
Is there any other way to capture in virtual box in whonix.
If there can u please help me.
