### ISSUE TITLE
How to install CIC flow meter in whonix workstation.

### ISSUE THREAD

**Issue by Msivachaithanyaprasad** [ahlashkari/CICFlowMeter#51]
Hai sir I have confusion. I installed the virtual box in windows os and in the virtual box I installed whonix Linux distribution. I created the whonix gateway and workstation. I need CIC flow meter for collecting the data so that I want to install CIC flow meter.
![1](https://user-images.githubusercontent.com/36365205/73268128-64fda880-4200-11ea-8f93-403a38acb3b4.PNG)
![2](https://user-images.githubusercontent.com/36365205/73268139-67f89900-4200-11ea-963e-d757896eef03.PNG)
![3](https://user-images.githubusercontent.com/36365205/73268148-6a5af300-4200-11ea-9791-3b06df779bcd.PNG)

1)(((https://www.unb.ca/cic/_assets/documents/cicflowmeter-4.zip))) Through these link I downloaded the CIC flowmeter.
2)(((sudo apt-get install libcap-dev ))) Through these I installed the libcap package in whonix workstation.
3) I Installed CIC flow meter in whonix workstation but it is in .bat format. I think (.bat) is only work in DOS and windows. I am unable to open it in whonix workstation.
4)((sudo ./CICFlowMeter)) for these command I am getting command not found in whonix wokstation.
5) (./cfm "inputFolder" "outputFolder") for these command I am getting command not found in whonix wokstation.

Please reply ...

**Comment by Logan-Davidson** [comment]
Your directory should be set to the bin folder in order to run the application

**Comment by Msivachaithanyaprasad** [comment]
Thank for your response.
But In whonix workstation it is in (.bat) format.

**Comment by Logan-Davidson** [comment]
in the first picture that you sent I see that you have both the windows versions (.bat), as we as the Unix versions (The two files with the purple icons)

**Comment by Msivachaithanyaprasad** [comment]
By clicking those purple icons nothing is opening.
I installed the CIC flowmeter outside the whonix work station in windows the same as in whonix workstation I got the 4 icons in bin folder. I opened the (CICflowmeter.bat) and windows command line opened and later CIC flow meter tab appeared.

![4](https://user-images.githubusercontent.com/36365205/73324777-27d1fe80-4272-11ea-8a4f-e5500b18e013.PNG)

But in whonix workstation, I installed the CIC flow meter and I opened the bin folder I got four Icons.
If I click (CICflowMeter.bat) nothing is coming. These are my problems.

![1](https://user-images.githubusercontent.com/36365205/73324851-71bae480-4272-11ea-9d15-3b01cb33cf8b.PNG)

![2](https://user-images.githubusercontent.com/36365205/73324879-813a2d80-4272-11ea-8c8f-1cb7a5b0e230.PNG)


Can u please help me.

**Comment by Msivachaithanyaprasad** [comment]
The only thing I need is I want to run the CIC flow meter inside the whonix workstation.
Can u give me the step by step approach it helps a lot?

**Comment by Logan-Davidson** [comment]
Open a terminal, set the directory to the bin folder holding the four files, and run "sudo ./CICFlowMeter"

**Comment by Msivachaithanyaprasad** [comment]
Thank you for your response.
I got it

**Comment by Msivachaithanyaprasad** [comment]
Why CIC flow meter is not loading in whonix workstation?
Can u please help me to resolve it.
![5](https://user-images.githubusercontent.com/36365205/73425768-adc87500-4358-11ea-8317-60517671f80f.PNG)

**Comment by ahlashkari** [comment]
CICFlowMeter has been configured for Ubuntu and Windows at this moment.

**Comment by Msivachaithanyaprasad** [comment]
So, I can't able to capture the data via whonix workstation with CIC flow meter?
What is another way to capture the tor or non-tor data (.pcap file) can u please help me!

**Comment by Msivachaithanyaprasad** [comment]
Thank u for your response, sir.
Hai sir,
If CIC flow meter is only configured with ubuntu and windows then how can I
capture the tor or nontor data (.pacap files) in virtual box in whonix (is
a Debian GNU/Linux–based security-focused Linux distribution).
Is there any other way to capture in virtual box in whonix.
If there can u please help me.

**Comment by ahlashkari** [comment]
No idea at this moment.

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
