### ISSUE TITLE
Why CIC flow meter is not loading in whonix workstation?

### ISSUE THREAD

**Issue by Msivachaithanyaprasad** [ahlashkari/CICFlowMeter#52]
Why CIC flow meter is not loading in whonix workstation?
Can u please help me to resolve it.
![5](https://user-images.githubusercontent.com/36365205/73425801-c33d9f00-4358-11ea-9dbe-85e7e06cf0e0.PNG)

**Comment by ahlashkari** [comment]
CICFlowMeter has been configured for Ubuntu and Windows at this moment.

**Comment by Msivachaithanyaprasad** [comment]
So, I can't able to capture the data via whonix workstation with CIC flow meter?
What is another way to capture the tor or non-tor data can u please help me!

**Comment by Msivachaithanyaprasad** [comment]
Thank u for your response, sir.
Hai sir,
If CIC flow meter is only configured with ubuntu and windows then how can I
capture the tor or nontor data (.pacap files) in virtual box in whonix (is
a Debian GNU/Linux–based security-focused Linux distribution).
Is there any other way to capture in virtual box in whonix.
If there can u please help me.

**Comment by ahlashkari** [comment]
No idea at this moment.
