### ISSUE TITLE
Can u please tell about your configuration how you collected more data within 5 seconds

### ISSUE THREAD

**Issue by Msivachaithanyaprasad** [ahlashkari/CICFlowMeter#56]
Hai sir,
Currently, I am doing a final year project I am Electronics background in India. At the time when I want to do a final year project, I choose your base paper because it is unique and it is different from other projects and I am spending a lot more time to understanding.

Later I saw your personal Information in UNB I Inspired by your projects. My area of interest is Network domain these are the reason I choose your project.

Thank you for your kind response sir.

Sir, at last, one request I have two last doubts can u please answer. I understood all the procedures and technical terms.

(1)  As u mentioned you captured the tor and non-tor traffic data using Tcpdump and Wireshark. After capturing by this way I gave (.pcap files) to the CIC FlowMeter as offline mode. In CIC flow Meter after entering it shown It listened to (1 pcap) file that's it. In CIC FlowMeter it is not shown any features.

(2) I captured the data by using CICFlowMeter in ubuntu and Whonix gateway in the virtual box. As u mentioned in the paper (merged_5s) you collected more data within 5 seconds.
I collected as In ubuntu as a workstation (270(.pcap files) non-tor) and in the host after gateway, I collected (70 (.pacp files) tor) in the duration of 30 minutes with 330kbps wi-fi speed.

                                                IN HOST(WINDOWS)
![host](https://user-images.githubusercontent.com/36365205/73666770-506e5400-46c9-11ea-8747-b5ad26e7b7b7.PNG)

                                               IN UBUNTU(IN VIRTUAL BOX)
![ubuntu](https://user-images.githubusercontent.com/36365205/73666825-624ff700-46c9-11ea-9e91-8fdcc7eca608.PNG)

Can u please tell about your configuration how you collected more data within 5 seconds?
Please answer sir.

**Comment by ahlashkari** [comment]
Hi,
In Tor dataset we used ISCXFlowMeter which is the old version of this flowmeter, not CICFlowMeter and I never retested our previous datasets with the new flowmeter. 
BTW, this is for FlowMeter not for Datasets, if you have any questions about datasets, pls send through the right channel.  
Good Luck,
