### ISSUE TITLE
CSV  headers Document

### ISSUE THREAD

**Issue by CCH0124** [ahlashkari/CICFlowMeter#57]
Is there a detailed description of the headers for generating CSV for this tool ?

**Comment by jujuno1** [comment]
Hello, for the CICIDS2017 dataset, the CSV file extracted with your tool is not consistent with the CSV dataset you published. Is the code you posted accurate?

**Comment by Logan-Davidson** [comment]
There is a list of all the features with description in the readMe.txt file
