### ISSUE TITLE
CICFlowMeter generating empty CSV files with 1 flow and all packets discarded

### ISSUE THREAD

**Issue by va-lt-02** [ahlashkari/CICFlowMeter#59]
Hi,
I have tested CIC flowmeter and sometimes doesn't work: all packets are discarded.
When this happens? 

Thanks

**Comment by alpha358** [comment]
Maybe the reason is somewhere here Cmp.java line:140 :
(the packet reader fails?)
```Java
            try{
                BasicPacketInfo basicPacket = packetReader.nextPacket();
                nTotal++;
                if(basicPacket !=null){
                    flowGen.addPacket(basicPacket);
                    nValid++;
                }else{
                    nDiscarded++;
                }
```

**Comment by a1139056159** [comment]
Hi,
Are you using IPv6 protocol? The same thing happend to me as well.
You can try to change:
CICFlowMeter/src/main/java/cic/cs/unb/ca/jnetpcap/worker/ReadPcapFileWorker.java (152, 153)
to:
boolean readIP6 = true;
boolean readIP4 = false;
then recompile it.

It works for me.

**Comment by Logan-Davidson** [comment]
It could also have to do with your flow timeout and activity timeout settings not accepting the packets.

**Comment by alpha358** [comment]
> Hi,
> Are you using IPv6 protocol? The same thing happend to me as well.
> You can try to change:
> CICFlowMeter/src/main/java/cic/cs/unb/ca/jnetpcap/worker/ReadPcapFileWorker.java (152, 153)
> to:
> boolean readIP6 = true;
> boolean readIP4 = false;
> then recompile it.
> 
> It works for me.

No I am not using IPv6, I have check this option already.

> flow timeout and activity timeout settings not accepting the packets

None of these options are changing the situation.

Look at [any UNSW-NB15 Dataset pcap file](https://cloudstor.aarnet.edu.au/plus/index.php/s/2DhnLGDdEECo4ys?path=%2FUNSW-NB15%20-%20pcap%20files%2Fpcaps%2017-2-2015), for all of them almost all packets are dropped.

Maybe the dataset pcap files are corrupted?

**Comment by souravs17031999** [comment]
@alpha358 did you solved this issue ?
@Logan-Davidson how did you select those timeout values , on what basis ?
