### ISSUE TITLE
What units are used for flow timeout and activity timeout in offline mode?

### ISSUE THREAD

**Issue by merahhh** [ahlashkari/CICFlowMeter#60]
Hi, I was using the offline mode and saw the default flow timeout and activity timeout were 120000000 and 5000000, respectively. Just wondering what these stand for and what unit is used? 
Sorry if I missed this in the documentation.

**Comment by dobinder** [comment]
Hallo, these seem to be microseconds. Therefore 120000000 µs = 5 minutes and 5000000 µs are 5 seconds.

**Comment by Logan-Davidson** [comment]
Dobinder is correct that it is in microseconds, however it converts to 2 minutes and 5 seconds
