### ISSUE TITLE
How to get the .jar file for this CICFlowMeter

### ISSUE THREAD

**Issue by LidiyaRaphiPulikkottil** [ahlashkari/CICFlowMeter#61]
how to install this to get gui

**Comment by tirth-cloudops** [comment]
even I had the same issue. When you download this file it is under the CICFlowMeterMaster name. I couldn't find the mentioned files over there. Sorry if I am missing any details.

**Comment by dobinder** [comment]
@LidiyaRaphiPulikkottil @tirth24 This package uses gradle to build. Simply clone the repository and run "gradle execute" to compile and run this tool. The GUI should then appear. Also you might need root privileges to start it.
