### ISSUE TITLE
how you have labelled port scan csv file.

### ISSUE THREAD

**Issue by Neelupcdac** [ahlashkari/CICFlowMeter#62]
on what basis you have labelled that this flow is port scan and that flow is benign.
how can we classify Port Scan label into different types of port scans in the CSV file?

**Comment by ahlashkari** [comment]
Labelling is a manual task and you need to understand the scenario and then label the flow using these fields: Source IP, Destination IP, Source Port, Destination Port, Protocol and Timestamp.
