### ISSUE TITLE
Possible incorrect calculation of Total Length of Fwd Packets 

### ISSUE THREAD

**Issue by wshwhyu** [ahlashkari/CICFlowMeter#64]
I have noticed that csv generated by the tool have incorrect calculation of Length of Fwd Packets .
Could you share the latest tools

**Comment by dobinder** [comment]
The length is calculated based on the length of the payload of each packet (The total length - the length of the the ip- and tcp/udp-headers).

**Comment by wshwhyu** [comment]
![QQ图片20200309011833](https://user-images.githubusercontent.com/16811625/76182685-94f77e80-61a4-11ea-948c-309bd0176577.png)
in this  picture,the author's data of  Total Length of Fwd Packets is 6 ,but mine is 0. could you check it for me. thanks

**Comment by wshwhyu** [comment]
@dobinder please see the pcap as above. The author's  dataset  that I filtered some as follows:
![QQ图片20200309012554](https://user-images.githubusercontent.com/16811625/76182781-f4ee2500-61a4-11ea-8db5-b8f7b55c00ff.png) 
But mine is different as follows:
![QQ图片20200309012728](https://user-images.githubusercontent.com/16811625/76182871-354da300-61a5-11ea-8667-14cbbdbc55b1.png)
could you check it for me .thanks

**Comment by wshwhyu** [comment]
@ahlashkari @gdraperg hi ,could you  see this problem for me.thanks

**Comment by wshwhyu** [comment]
@dobinder see https://github.com/ahlashkari/CICFlowMeter/issues/64.
hope your response. thanks.

**Comment by dobinder** [comment]
@wshwhyu which dataset are you using? I could imagine the dataset was created with a different version of this tool and therefore produced different results. But I can't tell for sure, because I'm not involved with the development.

**Comment by wshwhyu** [comment]
@dobinder  I use the dataset  of CICDatasetCIC-IDS-2017,and i choose  the data (Flow ID is 192.168.10.5-8.254.250.126-49188-80-6) from Monday-WorkingHours.pcap_ISCX.csv.  
I need this tool deal with dataset, and I  worry about data errors，so use the latest version ok?

**Comment by wshwhyu** [comment]
@ilfreedom hope your response. thanks.

**Comment by ahlashkari** [comment]
Hi Guys, pls remember that we have several version of FlowMeter and you need to find which version has been used for which dataset generation. BTW, as the package has been updated on the last month also, I am suggesting to use the last version and calculate the values again.
