### ISSUE TITLE
if one pcap file has one packet，why the cicflowmeter result is none except field names

### ISSUE THREAD

**Issue by wshwhyu** [ahlashkari/CICFlowMeter#66]
![image](https://user-images.githubusercontent.com/16811625/76195147-6e4a3f80-61c6-11ea-9f0b-7729acaf5ba8.png)
the CICFlowmeter result is as follows:,but why not have the one packet data ?
![image](https://user-images.githubusercontent.com/16811625/76195310-c41ee780-61c6-11ea-9fb1-10a8d64f4060.png)

**Comment by dobinder** [comment]
The saving of the data flows is done in the FlowGenerator (I think in the dumpLabeledFlowBasedFeatures function). There you can see that a flow is only saved if flow.packetCount() > 1 (Line 175 and 189). Therefore only flows with at least two contained packets are stored.

**Comment by wshwhyu** [comment]
@dobinder thank you very much.

**Comment by wshwhyu** [comment]
@dobinder see this question . could you help me?   Because I think you did a good job of this.thanks
https://github.com/ahlashkari/CICFlowMeter/issues/68

**Comment by wshwhyu** [comment]
@dobinder  see this question https://github.com/ahlashkari/CICFlowMeter/issues/68 . could you help me? Because I think you did a good job of this.thanks
