### ISSUE TITLE
how to remove the 100mb limit? thanks in advance

### ISSUE THREAD

**Issue by wshwhyu** [ahlashkari/CICFlowMeter#68]
hi ，how to remove the 100mb limit? 
Is pcap file maximum 100M or csv file maximum 100M? I'm confused about this .  I tried to process pcap data larger than 100M. The data can be parsed, but I don't know if the result is right. could you help me to explain it  .thanks.
![image](https://user-images.githubusercontent.com/16811625/76284214-9d9ca180-62d7-11ea-8b06-5bbe059bac0a.png)
@ahlashkari

**Comment by dobinder** [comment]
@wshwhyu I don't think this information is still up to date. I've already used the tool for pcap files with sizes of multiple GBs and it worked fine.

**Comment by wshwhyu** [comment]
@dobinder thank you very much.  I agree with you very much. 
I have another question for you. A data stream in wireshark as one flow(The same are Src IP \Src Port\Dst IP\Dst Port\Protocol), but use this tool, it split several flows as figure 2:
![image](https://user-images.githubusercontent.com/16811625/76308047-c35e8200-62a8-11ea-89c4-d5cefeb99129.png)
![image](https://user-images.githubusercontent.com/16811625/76308524-bd1cd580-62a9-11ea-88f8-a6f85c35d0f2.png)
This phenomenon also occurs in most other pcap data.I think it has something to do with the timeout setting.Do you know how to set it to be consistent with the results of wireshark.

**Comment by dobinder** [comment]
@wshwhyu That's correct, but this property is also intentional. A flow is always split into multiple flows if either the timeout value is exceeded or if a tcp packet contains a fin flag.

**Comment by wshwhyu** [comment]
@dobinder thank you very much.Appreciate your help.

**Comment by benholden09** [comment]
> @wshwhyu I don't think this information is still up to date. I've already used the tool for pcap files with sizes of multiple GBs and it worked fine.

Which version of cicflowmeter are you using as i am using 4.0 and i still get an issue with larger files
