### ISSUE TITLE
Does it support 6lowpan

### ISSUE THREAD

**Issue by a1139056159** [ahlashkari/CICFlowMeter#72]
Hi,

I collected pcap files from an IoT simulator. But jnetpcap seems not to support the 6lowpan protocol. Does anyone have some alternative way to extract features from pcap files?

Best.

**Comment by ahlashkari** [comment]
This project is for the Ethernet data structure and is not working for IoT.

**Comment by a1139056159** [comment]
Got it. Thanks.
