### ISSUE TITLE
I found that the new version and the old version have a few columns of data for the same data stream

### ISSUE THREAD

**Issue by wshwhyu** [ahlashkari/CICFlowMeter#74]
I found that the new version and the old version have a few columns of data for the same data stream as shown below. Is the latest version correct?
old version：
![image](https://user-images.githubusercontent.com/16811625/77824275-40c72680-70e0-11ea-8bd3-3ed4ebcdb4c2.png)

new version：
![image](https://user-images.githubusercontent.com/16811625/77824265-373dbe80-70e0-11ea-8ca2-4aaa4200b559.png)

          I find that the new version is different from the old version. Is the latest version correct

**Comment by ahlashkari** [comment]
Yes. Pls, do not use the old version any more as we changed and corrected several issues there.
