### ISSUE TITLE
Active statistics constantly equal to 0 on Friday Working Hours pcap from CICIDS-2017

### ISSUE THREAD

**Issue by KevinRiou22** [ahlashkari/CICFlowMeter#76]
Hello,
When executing CICFlowMeter on a pcap from CICIDS-2017 (friday working hours), I noticed that all the generated flows have active statistics equal to zero. 
When executing it in debug mode on eclipse, I noticed that active time should be updated in the following function (in /src/main/java/cic/cs/unb/ca/jnetpcap/BasicFlow.java) :

`    public void updateActiveIdleTime(long currentTime, long threshold){

    	if ((currentTime - this.endActiveTime) > threshold){
    		if((this.endActiveTime - this.startActiveTime) > 0){
	      		this.flowActive.addValue(this.endActiveTime - this.startActiveTime);	      		
    		}
    		this.flowIdle.addValue(currentTime - this.endActiveTime);
    		this.startActiveTime = currentTime;
    		this.endActiveTime = currentTime;
    	}else{
    		this.endActiveTime = currentTime;
    	}
    }`

This function seems to be called two times at all in the code.
 When receiving new packet from an existing flow, the function addPacket, from CICFlowMeter/src/main/java/cic/cs/unb/ca/jnetpcap/FlowGenerator.java, first directly calls updateActiveIdleTime (line 124) with packet timestamp as input :
`flow.updateActiveIdleTime(currentTimestamp,this.flowActivityTimeOut);`
Then in the next line (125), by calling flow.addPacket, the function detectUpdateSubflows (from  /src/main/java/cic/cs/unb/ca/jnetpcap/BasicFlow.java) is called :
`updateActiveIdleTime(packet.getTimeStamp() - sfLastPacketTS, 5000000L);`
Here, the problem is that updateActiveIdleTime is called with a difference of timestamps as input, while updateActiveIdleTime is waiting for a timestamp.

If you come back to updateActiveIdleTime code, you will notice that by giving a difference of timestamps as its input, currentTime will be far smaller than this.endActiveTime, so the if condition will not be true. The program goes to the else statement and updates this.endActiveTime with the small currentTime. 

Next time the program will receive a packet, updateActiveIdleTime will be first called with the timestamp of the packet. Maybe the first if statement will be checked, but this time, the second one :
`if((this.endActiveTime - this.startActiveTime) > 0)`
will not be checked because endActiveTime will be far smaller than startActiveTime.
Then updateActiveIdleTime will be called again by detectUpdateSubflows, assuring that endActiveTime keeps a difference of timestamps as value.
By debugging the code, it seems, that it loops like this until the end of the execution, and the code never checks both is statements in updateActiveIdleTime, so Active is never updated.

Maybe I missed something, but I would like to understand why all Active stats keep 0 values. Moreover, I didn't understand why updateActiveIdleTime is called in detectUpdateSubflows.

By removing the call to updateActiveIdleTime in detectUpdateSubflows, I got some results for active stats.

Finally, I was surprised, because on CICIDS, when looking to friday working hours generated labeled flows (afternoon DDos for instance), I found some active stats not equal to 0. 

Thanks.

**Comment by ahlashkari** [comment]
Thanks for the point. We changed it for the last project and didn't return it back to the public version. You can check the updated version.
