### ISSUE TITLE
Deprecated Gradle features were used in this build

### ISSUE THREAD

**Issue by Banyc** [ahlashkari/CICFlowMeter#77]
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

Besides, the README is so simplified that I could barely guess what java version it requires. Troubleshooting is a disaster.

**Comment by world0123** [comment]
Is the problem solved?
