### ISSUE TITLE
Flow timeout can not be passed to "cfm"

### ISSUE THREAD

**Issue by blackvvine** [ahlashkari/CICFlowMeter#78]
Hi,

I have noticed that the `cfm` command does not take in the flow and activity timeout values as an input. Are there any other ways to set the timeout values without manually setting the variables in `ReadPcapFileWorker.java` and building from scratch?

**Comment by Logan-Davidson** [comment]
There is no way to alter those values from command line, but as you said you are able to change the  values within the code, or you can use the App.java version in offline mode which takes them as inputs

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
