### ISSUE TITLE
can't find bin directory

### ISSUE THREAD

**Issue by daishu7** [ahlashkari/CICFlowMeter#8]
I can't find bin directory ,how to execute? please help me

**Comment by ahlashkari** [comment]
Hi,
The bin folder is for the binary version and here in Git we just have the source code. Either you can run the project and the compiler will generate the Bin folder for you or you can download the "Jar Package" from this link:
http://www.unb.ca/cic/research/applications.html#CICFlowMeter

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/
