### ISSUE TITLE
Mistake in BasicFlow.java to write bAvgBytesPerBulk value to csv.

### ISSUE THREAD

**Issue by ltkhang** [ahlashkari/CICFlowMeter#80]
Hi,

I read a whole code to transfer the code into python, when I read the code in https://github.com/ahlashkari/CICFlowMeter/blob/2b5b932bfc347f3cfbdd7e6fea3c3de822f7d33e/src/main/java/cic/cs/unb/ca/jnetpcap/BasicFlow.java#L1194, I realized a mistake. In this line, it should be "bAvgBytesPerBulk" instead of "fAvgBytesPerBulk". I think that this mistake will lead to wrong values in IDS dataset for machine learning.

Khang

**Comment by ahlashkari** [comment]
Thanks for the point.
