### ISSUE TITLE
CWE Flag

### ISSUE THREAD

**Issue by marksniper** [ahlashkari/CICFlowMeter#81]
Hi,
I was stumped on the flag CWE. I think the correct flag is the CWR, which means Congestion Window Reduced.
Could you please adjust the csv and update the documentations. I worked on the same project and I also fix the issue ( https://github.com/marksniper/FeatureExtractor ).
Benedetto Marco Serinelli

**Comment by ahlashkari** [comment]
Thanks, it was a typo.
