### ISSUE TITLE
Gradle execute giving error

### ISSUE THREAD

**Issue by JapsimarSinghWahi** [ahlashkari/CICFlowMeter#82]
Hi, 
I am not able to install the tool in linux machine. 
When I execute $gradle execute, I get an error saying -

![111](https://user-images.githubusercontent.com/23633009/82839578-d3e0ca80-9e9d-11ea-991a-829ad57a2f4f.PNG)

Can you help with the installing steps and converting a pcap to a csv file?

**Comment by ahlashkari** [comment]
You can use Maven instead.
