### ISSUE TITLE
Empty file after cli

### ISSUE THREAD

**Issue by QuentinFringhian** [ahlashkari/CICFlowMeter#83]
Hi !
I can't manage to obtain a non empty file after converting a pcap file to a csv file trough the cli version of this flow. my pcap file has more than 6K packets and the output file only has the name of the row... When I use a file with 6M packets it does work (well?).
Also, is that possible to have a clean version of the online capturing packet of the graphic version ? because I am obligated to use first WireShark to then convert with CiCFlow, it would be cool to directly use CiCFlow.
Thanks and have a good day.

**Comment by souravs17031999** [comment]
@QuentinFringhian did you solved this issue ?

**Comment by QuentinFringhian** [comment]
> @QuentinFringhian did you solved this issue ?

Sorry @souravs17031999, I did not solved this issue. I wish you good luck on your coding!
