### ISSUE TITLE
gradle execute is giving error when executing

### ISSUE THREAD

**Issue by tehnanali** [ahlashkari/CICFlowMeter#88]
gradle execute on linux is giving below error

root@kali:~/CICFlowMeter# gradle execute

> Configure project : 
type Jar
type JavaExec

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Class com.google.common.base.Predicates$ObjectPredicate$1 does not implement the requested interface java.util.function.Predicate

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

03:42:01.411 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClient] Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Could not resolve all dependencies for configuration ':compileClasspath'.] from daemon DaemonInfo{pid=2022, address=[5d539293-f34a-430d-8f7b-31f52b3e8f10 port:37441, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], state=Idle, lastBusy=1592464629092, context=DefaultDaemonContext[uid=c49ada4f-a5fe-4d8a-b27a-b19e6f7d4c96,javaHome=/usr/lib/jvm/java-11-openjdk-amd64,daemonRegistryDir=/root/.gradle/daemon,pid=2022,idleTimeout=10800000,daemonOpts=-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
03:42:01.413 [DEBUG] [org.gradle.launcher.daemon.client.DaemonClientConnection] thread 1: dispatching class org.gradle.launcher.daemon.protocol.Finished

**Comment by ahlashkari** [comment]
You can use Maven instead.

**Comment by tehnanali** [comment]
Ive used below maven to install the package
mvn install:install-file -Dfile=jnetpcap.jar -DgroupId=org.jnetpcap -DartifactId=jnetpcap -Dversion=1.4.1 -Dpackaging=jar
