### ISSUE TITLE
Can I use Real time mode with cli?

### ISSUE THREAD

**Issue by Vccxx** [ahlashkari/CICFlowMeter#90]
I am working on a project that need to run CICFlowMeter in realtime mode on a Centos machine without GUI.
But it seems that the cli mode of CICFlowMeter doesn't support realtime mode (the cfm.sh)
Do I need to modify the source code to achieve my goal ?
ps : I don't think tcpdump + CICFlowMeter is a good idea because the realtime flow may become incomplete when using rotate_seconds (-z paramater) to save and process pcaps.

**Comment by Vccxx** [comment]
If I use command like this : 
`./cfm test_pcap_dir output_dir`
and the test_pcap_dir contains two pcap files, each one contains part of the packet belongs to one tcp flow.
Will CICFlowMeter realize this situation and calculate the output correctly (with only one line output in the output csv)?

**Comment by dufq** [comment]
I have the same the demands，did you solve the problem ?

**Comment by padraigmc** [comment]
Also looking to achieve the same, is there any update on this?

**Comment by stjordanis** [comment]
> Also looking to achieve the same, is there any update on this?
https://gitlab.com/hieulw/cicflowmeter
sniff packets real-time from interface to flow csv: (need root permission)
cicflowmeter -i eth0 -c flows.csv
Also, check this https://github.com/iPAS/TCPDUMP_and_CICFlowMeter

**Comment by stjordanis** [comment]
> I am working on a project that need to run CICFlowMeter in realtime mode on a Centos machine without GUI.
> But it seems that the cli mode of CICFlowMeter doesn't support realtime mode (the cfm.sh)
> Do I need to modify the source code to achieve my goal ?
> ps : I don't think tcpdump + CICFlowMeter is a good idea because the realtime flow may become incomplete when using rotate_seconds (-z paramater) to save and process pcaps.

@ahlashkari Could you  please add  a way to use cfm with arguments like cfm -i eth0 -c flows.csv to run in real time from the command line, without the java gui?

**Comment by ahlashkari** [comment]
Hi,
We are pleased to announce that the first version of the Network and Transportation Layers Flow Analyzer ([NTLFlowLyzer](https://github.com/ahlashkari/NTLFlowLyzer)) is now available as part of the Understanding Cybersecurity Series (UCS) knowledge mobilization program. This Python open-source project has been designed and developed to address many issues encountered with CICFlowMeter. It extracts over 300 features from TCP-based network traffic, tailored explicitly for Anomaly Profiling (AP). NTLFlowLyzer serves as a key component of the upcoming NetFlowLyzer.

https://github.com/ahlashkari/NTLFlowLyzer

Best,
BCCC Team
https://www.yorku.ca/research/bccc/

**Comment by dufq** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已收到。我尽快给您回复。
