### ISSUE TITLE
In Windows 10 library jnetpcap cannot be initialized

### ISSUE THREAD

**Issue by RyuAsuka** [ahlashkari/CICFlowMeter#93]
When the GUI is running, click "Load" button but nothing happens. 

The debug log shows:

`2020-07-25 13:21:13 DEBUG cic.cs.unb.ca.flow.ui.FlowMonitorPane    java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
2020-07-25 13:21:13 DEBUG cic.cs.unb.ca.flow.ui.FlowMonitorPane    java.lang.UnsatisfiedLinkError: com.slytechs.library.NativeLibrary.dlopen(Ljava/lang/String;)J
2020-07-25 13:22:36 DEBUG cic.cs.unb.ca.flow.ui.FlowMonitorPane    java.lang.NoClassDefFoundError: Could not initialize class org.jnetpcap.Pcap`

However there is no exceptions in the process of building. And the same program performances normally in Linux system.

**Comment by byamao1** [comment]
Please read `RELEASE_NOTES.txt` and `README.md`  carefully.
1.Win32 Dependency: jNetPcap requires WinPcap 3.1 or greater installed.  WinPcap version 4.0.1 or greater is recommended, but not  neccessary. (http://winpcap.org)
2.copy the jnetpcap.dll library file, found at root of jnetpcap's installation directory to one of the window's system folders. This could be \windows or \windows\system32 directory.
3.Install jnetpcap local repo
