### ISSUE TITLE
CICFlowMeter generates no output for CICIDS2018 pcap files- Windows 

### ISSUE THREAD

**Issue by mariasimi** [ahlashkari/CICFlowMeter#98]
Hi,
I build CICFlowMeter using Eclipse on Windows 10.
When I input a pcap file the following message appears: "CICFlowMeter has received 1 pcap file" and nothing happens.
I have tried to use it on one pcap file of the CICIDS2018 dataset.

I also tried the suggestion of  issue #22 (copied the jnet-pcap.dll and jnetpcap-100pcap.dll to the java root folder on windows) however this also does not change anything and no output is generated.

**Comment by zomorod-a** [comment]
Hello
I had the same problem.
But If you install JDK (Java SE Development Kit 8u261), the problem will be solved :)
